apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: auth-db
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: auth-db
    spec:
      containers:
        - name: auth-db
          env:
          - name: POSTGRES_DB
            value: kwetter.AuthService
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          image: postgres:14.7-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-db
      hostname: auth-db
      restartPolicy: Always
      volumes:
        - name: auth-db
          persistentVolumeClaim:
            claimName: auth-db
status: {}
