apiVersion: v1
kind: PersistentVolumeClaim
metadata:

  labels:
    io.kompose.service: profile-db
  name: profile-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
