apiVersion: v1
kind: PersistentVolumeClaim
metadata:

  labels:
    io.kompose.service: rabbitmq-claim2
  name: rabbitmq-claim2
spec:
  securityContext:  # Move the securityContext section outside the containers section
    runAsUser: 0
    runAsGroup: 0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
