apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)

  labels:
    io.kompose.service: report-db
  name: report-db
spec:
  ports:
    - name: "5436"
      port: 5436
      targetPort: 5432
  selector:
    io.kompose.service: report-db
status:
  loadBalancer: {}
