apiVersion: v1
kind: PersistentVolumeClaim
metadata:

  labels:
    io.kompose.service: tweet-db
  name: tweet-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
