apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)

  labels:
    io.kompose.service: tweet-db
  name: tweet-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tweet-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)

      labels:
        io.kompose.service: tweet-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: Kwtter.TweetService
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:14.7-alpine
          name: tweet-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: tweet-db
      hostname: tweet-db
      restartPolicy: Always
      volumes:
        - name: tweet-db
          persistentVolumeClaim:
            claimName: tweet-db
status: {}
