<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_iddMUoaVXwbcwja</name>
   <tag></tag>
   <elementGuidId>38df403e-1ff3-450e-9389-6cdd2af3162e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.MuiBox-root-20.FlexItem.FlexRow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='0']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root MuiBox-root-20 FlexItem FlexRow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iddMUoaVXwbcwja</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;content&quot;]/div[@class=&quot;root&quot;]/div[@class=&quot;results&quot;]/div[@class=&quot;MuiPaper-root listContainer MuiPaper-elevation1 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root list MuiList-padding&quot;]/div[@id=&quot;0&quot;]/div[@class=&quot;MuiBox-root MuiBox-root-19 FlexItem FlexColumn&quot;]/div[@class=&quot;MuiBox-root MuiBox-root-20 FlexItem FlexRow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hCdJzoqFDvQGvvN'])[1]/preceding::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
