apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: authservice
  name: authservice
spec:
  ports:
    - name: "4002"
      port: 4002
      targetPort: 4002
  selector:
    io.kompose.service: authservice
status:
  loadBalancer: {}
