apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)

  labels:
    io.kompose.service: commentservice
  name: commentservice
spec:
  ports:
    - name: "4006"
      port: 4006
      targetPort: 4006
  selector:
    io.kompose.service: commentservice
status:
  loadBalancer: {}
