apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)

  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)

      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:4000
            - name: AuthServer
              value: http://authservice:4002
          image: docker.io/joepvand/backend_gateway
          name: gateway
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
