apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)

  labels:
    io.kompose.service: reportservice
  name: reportservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reportservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)

      labels:
        io.kompose.service: reportservice
    spec:
      containers:
        - env:
            - name: ConnectionStrings__DefaultConnection
              value: mongodb://report-db:27017/kwetter.ReportService
            - name: RabbitMQConnectionString
              value: amqp://mifszlfj:wQ1UqKrNr9BeWrlZwLQluDMqhFQBPOLo@goose.rmq2.cloudamqp.com/mifszlfj
          image: docker.io/martijnweber/reportservice
          name: reportservice
          ports:
            - containerPort: 4007
          resources: {}
      hostname: reportservice
      restartPolicy: Always
status: {}
