apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)

  labels:
    io.kompose.service: report-db
  name: report-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: report-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: report-db
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          image: mongo
          name: report-db
          ports:
            - containerPort: 27017
      hostname: report-db
      restartPolicy: Always
      volumes:
        - name: report-db
          persistentVolumeClaim:
            claimName: report-db
status: {}
