apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f ../docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)

  labels:
    io.kompose.service: tweetservice
  name: tweetservice
spec:
  ports:
    - name: "4003"
      port: 4003
      targetPort: 4003
  selector:
    io.kompose.service: tweetservice
status:
  loadBalancer: {}
