name: Docker Image CI / dockerhub

on:
  push:
    branches: [ "main" ]
    paths:
      - Backend/**

jobs:

  build_TweetService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        cd Backend
        docker build . --file ./TweetService/TweetService.Api/Dockerfile --tag martijnweber/tweetservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        cd TweetService/TweetService.Api
        docker push martijnweber/tweetservice:latest
  build_ProfileService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        cd Backend
        docker build . --file ./ProfileService/ProfileService.Api/Dockerfile --tag martijnweber/profileservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        cd ProfileService
        docker push martijnweber/profileservice:latest
  build_AuthService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        cd Backend
        docker build . --file ./Auth/AuthService.Api/Dockerfile --tag martijnweber/authservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push martijnweber/authservice:latest
  build_PostScanner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        cd Backend
        docker build . --file ./PostScanner/PostScanner/Dockerfile --tag martijnweber/postscanner:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push martijnweber/postscanner:latest
  build_Gateway:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        cd Backend
        docker build . --file ./Gateway/Dockerfile --tag martijnweber/gateway:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push martijnweber/gateway:latest
  build_ReportService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        cd Backend
        docker build . --file ./ReportService/ReportService.Api/Dockerfile --tag martijnweber/reportservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push martijnweber/reportservice:latest
  build_CommentService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        cd Backend
        docker build . --file ./CommentService/CommentService.Api/Dockerfile --tag martijnweber/commentservice:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push martijnweber/commentservice:latest
