name: .NET Build
on:
  push:
    branches:
      - main
    paths:
      - Backend/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - Backend/**
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Setup the .NET Core workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: cd Backend && dotnet restore Kwetter.sln
    - name: Build
      run: dotnet build --no-restore

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: |
        cd UnitTests
        dotnet test
